Add context menu command support
ist-bot-team/ist-discord-bot pull request #100
Opened 2022-10-15 13:50 UTC by RafDevX

2022-10-15 13:54 UTC, RafDevX commented
Things to consider:
- whether to split `UserContextMenuCommands` and `MessageContextMenuCommands` from the get-go (vs. current solution of checking inside a unified handler); see https://github.com/ist-bot-team/ist-discord-bot/pull/100/files#diff-0c14a37a0833070d83b1840afa4f70d830ccf1dd45cfc2f69d783aaea9ae1c1aR37
- how to improve command logging format (audit, not debug) to look better / potentially include more information; see [`utils.stringifyContextMenuCommand`](https://github.com/ist-bot-team/ist-discord-bot/pull/100/files#diff-df34984041fefc50027ab0d898cb89d41c3c3716a9372c0a8dadcf9982bac56eR156)

Thoughts, @diogotcorreia?

2022-10-15 19:40 UTC, diogotcorreia commented
@RafDevX 

- I'd split them. When registering the command, it can only be of one type (from what I've seen, if I'm wrong this does not apply then). Therefore, it'd make sense for the handler to be only of that type.
- Seems good to me as it is tbh

2022-10-16 14:51 UTC, RafDevX commented
I've decided against splitting it as there would be no way to actually type-check on runtime.

I can tell TypeScript that the handler accepts a `MessageContextMenuInteraction` but, in the end, there's nothing stopping someone from registering both a Message and a User command with the same name* - which would be translated into the same handler (and one of them would error, expecting it the interaction to be of type X when it's of type Y).

As such, I think the best way to do this is to just use type guards inside handlers (through `isMessageContextMenuCommand` and `isUserContextMenuCommand`), as originally designed.

*as far as I can tell, Discord allows this (I just tested it)

2022-10-16 14:54 UTC, diogotcorreia requested changes

2022-10-16 14:54 UTC, diogotcorreia commented on src/bot.d.ts
> +	// TODO: possibly split into Message and User here
Remove TODO

2022-10-16 14:54 UTC, diogotcorreia commented on src/modules/utils.ts
> +		throw new Error("Unknown command type");
Add a `logger.error({ interaction }, "Failed to stringify command due to unknown type)` here

2022-10-16 15:13 UTC, diogotcorreia approved these changes

2022-10-16 15:13 UTC, merged