Role Selection
ist-bot-team/ist-discord-bot pull request #52
Opened 2021-08-17 00:01 UTC by RafDevX

Closes #51

2021-08-30 18:46 UTC, diogotcorreia requested changes

2021-08-30 18:46 UTC, diogotcorreia commented on src/prisma/schema.prisma
> +    url      = env("DATABASE_URL")
There is no documentation on README on how to setup this on `docker-compose.yml`.

Possibly
```yml
build:
  context: .
  args:
    DATABASE_URL: "file:/app/data/bot.db"
```

2021-08-30 18:46 UTC, diogotcorreia commented on Dockerfile
> +ENV DATABASE_URL ${DATABASE_URL}
Even with this, migrations aren't automatically applied when the Docker container starts!

2021-08-30 20:26 UTC, RafDevX commented on src/modules/populate.ts
> +		});
It's mock data for testing, the whole populate module probably shouldn't even be called in production and probably shouldn't even be in version control but I'm not sure how to organize this.

2021-09-05 13:01 UTC, RafDevX commented on Dockerfile
> +ENV DATABASE_URL ${DATABASE_URL}
¯\_(ツ)_/¯

2021-09-05 21:23 UTC, diogotcorreia requested changes

2021-09-05 21:23 UTC, diogotcorreia commented on README.md
> +			GUILD_ID: PLACE_MAIN_GUILD_ID_HERE # or "GLOBAL" to use in multiple guilds (1hr roll-out time)
change all to spaces

2021-09-05 22:57 UTC, RafDevX commented on README.md
> +			GUILD_ID: PLACE_MAIN_GUILD_ID_HERE # or "GLOBAL" to use in multiple guilds (1hr roll-out time)
fixed

2021-09-06 10:54 UTC, diogotcorreia approved these changes

2021-09-06 10:55 UTC, merged